/*
 * generated by Xtext
 */
package cz.cuni.mff.d3s;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KarelRuntimeModule extends cz.cuni.mff.d3s.AbstractKarelRuntimeModule {

}
