/*
* generated by Xtext
*/
package cz.cuni.mff.d3s.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class KarelTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
