/*
 * generated by Xtext
 */
package cz.cuni.mff.d3s.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KarelUiModule extends cz.cuni.mff.d3s.ui.AbstractKarelUiModule {
	public KarelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
