
/*
 * generated by Xtext
 */
 
package cz.cuni.mff.d3s.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class KarelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return cz.cuni.mff.d3s.ui.internal.KarelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return cz.cuni.mff.d3s.ui.internal.KarelActivator.getInstance().getInjector("cz.cuni.mff.d3s.Karel");
	}
	
}
