/*
* generated by Xtext
*/
package cz.cuni.mff.d3s.ui.contentassist;

import cz.cuni.mff.d3s.ui.contentassist.AbstractKarelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class KarelProposalProvider extends AbstractKarelProposalProvider {

}
